doc: Add doc for multiple senders feature
moira-alert/doc pull request #126
Opened 2024-04-02 08:38 UTC by almostinf

2024-04-02 11:19 UTC, kissken commented on api.example.yml
> +  contacts_template:
хм, мы потом в релиз ноуты напишем, что сломали тут?

2024-04-02 11:20 UTC, Tetrergeru commented on notifier.example.yml
> +  # "sender_type" - characterizes the specific structure of the sender in the code
Не хочешь доку по конкретному полю повесить на это самое поле?

2024-04-02 11:20 UTC, kissken commented on api.example.yml
> +  contacts_template:
давай еще прям в примере покажем, как множественные задавать?

2024-04-02 12:03 UTC, almostinf commented on api.example.yml
> +  contacts_template:
Да, я думаю в релиз ноутсах написать, как переехать со старого формата на новый

2024-04-02 12:03 UTC, almostinf commented on api.example.yml
> +  contacts_template:
по поводу невалидного не до конца понял, это файлы с корректным конфигом

2024-04-02 12:04 UTC, almostinf commented on notifier.example.yml
> +  # "sender_type" - characterizes the specific structure of the sender in the code
там эти поля просто потом дублируются у каждого сендера, я подумал, что проще будет просто 1 раз написать описание

2024-04-02 12:05 UTC, Tetrergeru requested changes

2024-04-02 12:05 UTC, Tetrergeru commented on source/installation/webhooks_scripts.rst
> +if the request body in the config is empty.
```suggestion
if the request `body` in the config is empty.
```

2024-04-02 12:06 UTC, Tetrergeru commented on notifier.example.yml
> +  # "sender_type" - characterizes the specific structure of the sender in the code
Ну можно один раз у первого поля написать

2024-04-02 12:10 UTC, almostinf commented on api.example.yml
> +  contacts_template:
Добавил пример создания множественных вебхуков

2024-04-02 12:12 UTC, almostinf commented on notifier.example.yml
> +  # "sender_type" - characterizes the specific structure of the sender in the code
Окей, так и сделал

2024-04-02 12:48 UTC, almostinf commented on api.example.yml
> +  contacts_template:
И сделал сноску в `installation/configurations.yml` про то, что сервис не подымется с невалидным конфигом

2024-04-02 14:51 UTC, Tetrergeru approved these changes

2024-04-03 05:56 UTC, kissken approved these changes

2024-04-04 06:21 UTC, merged