Add slack icons doc
moira-alert/doc pull request #35
Opened 2019-01-15 11:46 UTC by kamaev

2019-01-15 19:09 UTC, borovskyav approved these changes

2019-01-15 19:09 UTC, borovskyav commented
Мне все нравится, добавил Сашу с Лешей, чтобы они посмотрели. https://moira.readthedocs.io/en/feature-slack_icons/installation/configuration.html#slack-icons

2019-01-16 08:18 UTC, beevee requested changes
Предлагаю везде писать Slack с заглавной, т.к. имя собственное.

2019-01-16 08:18 UTC, beevee commented on source/changelog.rst
> +- Feature usage of icons in slack notifications `moira-alert/moira#180 <https://github.com/moira-alert/moira/issues/180>`_. See more: :ref:`slack-icons`.
```suggestion
- Feature usage of icons in Slack notifications `moira-alert/moira#180 <https://github.com/moira-alert/moira/issues/180>`_. See more: :ref:`slack-icons`.
```

2019-01-16 08:18 UTC, beevee commented on source/installation/configuration.rst
> +By default slack sender won't change default icon configured for your bot. To use state-specific icons in notifications:
```suggestion
By default Slack sender won't change default icon configured for your bot. To use state-specific icons in notifications:
```

2019-01-16 08:18 UTC, beevee commented on source/installation/configuration.rst
> +- Add icons from ``..icons/slack`` directory as custom emojis according to their filenames to `slack <https://get.slack.help/hc/en-us/articles/206870177-Add-custom-emoji>`_
```suggestion
- Add icons from ``..icons/slack`` directory as custom emojis according to their filenames to `Slack <https://get.slack.help/hc/en-us/articles/206870177-Add-custom-emoji>`_
```

2019-01-16 08:18 UTC, beevee commented on source/installation/configuration.rst
> +- Set ``use_emoji`` to ``true`` for slack sender section in notifier configuration file
```suggestion
- Set ``use_emoji`` to ``true`` for Slack sender section in notifier configuration file
```

2019-01-16 13:09 UTC, sashasushko requested changes

2019-01-16 13:09 UTC, sashasushko commented on source/installation/configuration.rst
> +- Add icons from ``..icons/slack`` directory as custom emojis according to their filenames to `slack <https://get.slack.help/hc/en-us/articles/206870177-Add-custom-emoji>`_
Я прочёл документацию и не понял, какие имена давать моим кастомным emoji, а кажется, что это важно.

2019-01-16 13:10 UTC, sashasushko commented on source/installation/configuration.rst
> +- Add icons from ``..icons/slack`` directory as custom emojis according to their filenames to `slack <https://get.slack.help/hc/en-us/articles/206870177-Add-custom-emoji>`_
А не, это я балда

2019-01-16 13:11 UTC, sashasushko approved these changes

2019-01-17 10:02 UTC, kamaev commented
Влил все правки

2019-01-17 19:02 UTC, beevee approved these changes

2019-01-17 19:03 UTC, merged