Updated redis section in example configs
moira-alert/doc pull request #83
Opened 2021-10-20 08:30 UTC by dmitryanchikov

This PR updates redis section in config examples for checker, filter, api and notifier to accomadate changes with moving to go-redis.

2021-10-20 12:04 UTC, zhelyabuzhsky approved these changes

2021-10-26 07:22 UTC, KiskachiMaria approved these changes

2021-12-06 07:13 UTC, zhelyabuzhsky requested changes

2021-12-06 07:13 UTC, zhelyabuzhsky commented on api.example.yml
> +  #	with a timeout instead of blocking. Default is 3 seconds.
```suggestion
  # with a timeout instead of blocking. Default is 3 seconds.
```

2021-12-06 07:13 UTC, zhelyabuzhsky commented on filter.example.yml
> +  #	with a timeout instead of blocking. Default is 3 seconds.
```suggestion
  # with a timeout instead of blocking. Default is 3 seconds.
```

2021-12-06 07:13 UTC, zhelyabuzhsky commented on notifier.example.yml
> +  #	with a timeout instead of blocking. Default is 3 seconds.
```suggestion
  # with a timeout instead of blocking. Default is 3 seconds.
```

2022-02-25 09:57 UTC, zhelyabuzhsky approved these changes

2022-02-25 09:58 UTC, merged